apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: <your-docker-repo>/appointment-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
